"""Tests for factory.spec.parser — Markdown parsing of GRAPH-SPEC.md."""

from __future__ import annotations

from pathlib import Path

import pytest

from factory.spec.parser import (
    RepoSpec,
    parse_spec,
)

SAMPLE_SPEC = """\
# GRAPH-SPEC

Status: Auto-generated by re:factory

## Normative Language

The key words `MUST`, `MUST NOT`, `REQUIRED`, `SHOULD`, `SHOULD NOT`,
`RECOMMENDED`, `MAY`, and `OPTIONAL` in this document are to be interpreted as
described in RFC 2119.

## 1. Project Identity

- **Name:** test-factory
- **Type:** CLI tool
- **Language:** Python 3.11+
- **Framework:** None
- **Package Manager:** uv
- **Entry Point:** `factory.cli:main`

## 2. Goals

Define a meta-harness that orchestrates coding agents through bounded,
measurable, reversible SDLC cycles.

## 3. Technical Stack

### 3.1 Dependencies

- `structlog` — structured logging
- `pydantic` — domain models

### 3.2 External Dependencies

- `claude` CLI — agent subprocess runtime

## 4. Architecture

### 4.1 Abstraction Levels

1. **CLI Layer** — command dispatch, argument parsing
2. **Data Layer** — models, store, registry
3. **Core Layer** — spec generation and validation

### 4.2 Module Graph

#### 4.2.1 cli
- **Path:** `factory/cli.py`
- **Layer:** CLI
- **Classification:** hub
- **Role:** CLI entry point for the factory
- **Exports:** main, build_parser
- **Depends on:** store, eval, spec
- **Contracts owned:** none

#### 4.2.2 store
- **Path:** `factory/store.py`
- **Layer:** Data
- **Classification:** hub
- **Role:** Experiment store managing .factory/ directory
- **Exports:** ExperimentStore
- **Depends on:** models
- **Contracts owned:** ExperimentRecord

#### 4.2.3 models
- **Path:** `factory/models.py`
- **Layer:** Data
- **Classification:** hub
- **Role:** All Pydantic v2 strict models
- **Exports:** ProjectState, FactoryConfig, EvalProfile
- **Depends on:** none
- **Contracts owned:** ProjectState, FactoryConfig, EvalProfile

#### 4.2.4 spec
- **Path:** `factory/spec/`
- **Layer:** Core
- **Classification:** leaf
- **Role:** Repo spec generation and validation
- **Exports:** generate_spec, validate_spec
- **Depends on:** models, store
- **Contracts owned:** RepoSpec

#### 4.2.5 utils
- **Path:** `factory/utils.py`
- **Layer:** Core
- **Classification:** leaf
- **Role:** Shared utility functions
- **Exports:** slugify
- **Depends on:** none
- **Contracts owned:** none

### 4.3 Dependency Edges

| Source | Target | Import Type | Coupling | Surface |
|--------|--------|-------------|----------|---------|
| cli | store | direct | strong | `ExperimentStore.begin()` |
| cli | eval | direct | strong | `run_eval()` |
| cli | spec | direct | weak | `generate_spec()` |
| store | models | direct | strong | `ExperimentRecord` |
| spec | models | direct | strong | `EvalProfile` |
| spec | store | direct | weak | `ExperimentStore` |

### 4.4 Shared Contracts

#### ProjectState
- **Defined in:** models
- **Type:** Pydantic model
- **Consumers:** cli, store, eval
- **Change Risk:** high (3 consumers)

#### FactoryConfig
- **Defined in:** models
- **Type:** Pydantic model
- **Consumers:** cli, store
- **Change Risk:** medium (2 consumers)

#### ExperimentRecord
- **Defined in:** store
- **Type:** Pydantic model
- **Consumers:** cli
- **Change Risk:** low (1 consumer)

### 4.5 Entry Points

| Type | Module | Detail |
|------|--------|--------|
| CLI | cli | `factory` |
| CLI | spec | `factory spec generate` |

## 5. Change Impact

| If Changed | Affects | Reason | Severity |
|------------|---------|--------|----------|
| models | cli, store, spec | Central type definitions | **high** |
| store | cli, spec | Experiment lifecycle interface | **medium** |
| cli | — | Top-level entry point | **low** |
| spec | — | No dependents | **low** |
| utils | — | No dependents | **low** |

## 6. Coupling Metrics

| Module | Ca (afferent) | Ce (efferent) | I (instability) | Classification |
|--------|--------------|--------------|-----------------|----------------|
| models | 3 | 0 | 0.00 | hub (stable core) |
| store | 2 | 1 | 0.33 | hub |
| cli | 0 | 3 | 1.00 | leaf (entry point) |
| spec | 0 | 2 | 1.00 | leaf |
| utils | 0 | 0 | 0.00 | leaf |
"""


@pytest.fixture
def spec_file(tmp_path: Path) -> Path:
    p = tmp_path / "GRAPH-SPEC.md"
    p.write_text(SAMPLE_SPEC)
    return p


class TestParseIdentity:
    def test_parses_name(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.name == "test-factory"

    def test_parses_type(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.project_type == "CLI tool"

    def test_parses_language(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.language == "Python 3.11+"

    def test_parses_framework(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.framework == "None"

    def test_parses_package_manager(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.package_manager == "uv"

    def test_parses_entry_point(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.entry_point == "factory.cli:main"


class TestParseGoals:
    def test_parses_goals(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "meta-harness" in spec.goals
        assert "SDLC cycles" in spec.goals


class TestParseAbstractionLevels:
    def test_parses_levels(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.abstraction_levels) == 3
        assert "CLI Layer" in spec.abstraction_levels
        assert "Data Layer" in spec.abstraction_levels
        assert "Core Layer" in spec.abstraction_levels


class TestParseModules:
    def test_parses_all_modules(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.modules) == 5
        names = [m.name for m in spec.modules]
        assert names == ["cli", "store", "models", "spec", "utils"]

    def test_module_path(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        cli = spec.get_module("cli")
        assert cli is not None
        assert cli.path == "factory/cli.py"

    def test_module_role(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        store = spec.get_module("store")
        assert store is not None
        assert store.role == "Experiment store managing .factory/ directory"

    def test_module_layer(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        models = spec.get_module("models")
        assert models is not None
        assert models.layer == "Data"

    def test_module_classification(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        cli = spec.get_module("cli")
        assert cli is not None
        assert cli.classification == "hub"

    def test_module_exports(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        models = spec.get_module("models")
        assert models is not None
        assert models.exports == ["ProjectState", "FactoryConfig", "EvalProfile"]

    def test_module_depends_on(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        cli = spec.get_module("cli")
        assert cli is not None
        assert cli.depends_on == ["store", "eval", "spec"]

    def test_module_contracts_owned(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        store = spec.get_module("store")
        assert store is not None
        assert store.contracts_owned == ["ExperimentRecord"]

    def test_contracts_owned_none(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        cli = spec.get_module("cli")
        assert cli is not None
        assert cli.contracts_owned == []

    def test_depends_on_none(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        models = spec.get_module("models")
        assert models is not None
        assert models.depends_on == []


class TestParseDependencyEdges:
    def test_parses_all_edges(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.dependency_edges) == 6

    def test_edge_source_target(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        edge = spec.dependency_edges[0]
        assert edge.source == "cli"
        assert edge.target == "store"

    def test_edge_import_type(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        edge = spec.dependency_edges[0]
        assert edge.import_type == "direct"

    def test_edge_coupling(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        weak_edge = next(e for e in spec.dependency_edges if e.coupling == "weak")
        assert weak_edge.source == "cli"
        assert weak_edge.target == "spec"

    def test_edge_surface(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        edge = spec.dependency_edges[0]
        assert "ExperimentStore" in edge.surface


class TestParseSharedContracts:
    def test_parses_all_contracts(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.shared_contracts) == 3

    def test_contract_name(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.shared_contracts[0].name == "ProjectState"

    def test_contract_defined_in(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.shared_contracts[0].defined_in == "models"

    def test_contract_consumers(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.shared_contracts[0].consumers == ["cli", "store", "eval"]

    def test_contract_change_risk(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "high" in spec.shared_contracts[0].change_risk


class TestParseEntryPoints:
    def test_parses_all_entry_points(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.entry_points) == 2

    def test_entry_point_fields(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        ep = spec.entry_points[0]
        assert ep.name == "CLI"
        assert ep.module == "cli"


class TestParseChangeImpact:
    def test_parses_all_impacts(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.change_impact) == 5

    def test_impact_fields(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        imp = spec.change_impact[0]
        assert imp.module == "models"
        assert "cli" in imp.affects
        assert "high" in imp.severity.lower()

    def test_impact_no_affects(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        utils_impact = next(i for i in spec.change_impact if i.module == "utils")
        assert utils_impact.affects == []


class TestParseCouplingMetrics:
    def test_parses_all_metrics(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.coupling_metrics) == 5

    def test_metric_values(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        models_m = next(m for m in spec.coupling_metrics if m.module == "models")
        assert models_m.ca == 3
        assert models_m.ce == 0
        assert models_m.instability == 0.0
        assert "hub" in models_m.classification

    def test_unstable_module(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        cli_m = next(m for m in spec.coupling_metrics if m.module == "cli")
        assert cli_m.instability == 1.0


class TestGetModule:
    def test_case_insensitive(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.get_module("CLI") is not None
        assert spec.get_module("cli") is not None

    def test_not_found(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.get_module("nonexistent") is None


class TestParseSpecErrors:
    def test_file_not_found(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            parse_spec(tmp_path / "missing.md")

    def test_empty_spec(self, tmp_path: Path) -> None:
        p = tmp_path / "empty.md"
        p.write_text("")
        spec = parse_spec(p)
        assert isinstance(spec, RepoSpec)
        assert spec.modules == []
        assert spec.dependency_edges == []

    def test_spec_with_no_tables(self, tmp_path: Path) -> None:
        p = tmp_path / "notables.md"
        p.write_text(
            "# GRAPH-SPEC\n\n## 4. Architecture\n\n### 4.2 Module Graph\n\n"
            "#### 4.2.1 alpha\n- **Path:** `src/alpha`\n"
        )
        spec = parse_spec(p)
        assert len(spec.modules) == 1
        assert spec.modules[0].name == "alpha"
        assert spec.dependency_edges == []


class TestBackwardCompatibility:
    def test_old_format_modules_section(self, tmp_path: Path) -> None:
        """Ensure the parser still handles the old ## Modules / ### name format."""
        p = tmp_path / "old_format.md"
        p.write_text(
            "# Repo Spec\n\n## Modules\n\n### cli\n"
            "- **Path:** factory/cli.py\n- **Role:** Entry point\n"
            "- **Depends on:** store\n"
        )
        spec = parse_spec(p)
        assert len(spec.modules) == 1
        assert spec.modules[0].name == "cli"
        assert spec.modules[0].depends_on == ["store"]
