"""Tests for factory.spec.impact — module impact subgraph extraction."""

from __future__ import annotations

from pathlib import Path

import pytest

from factory.spec.impact import get_impact

SAMPLE_SPEC = """\
# GRAPH-SPEC

Status: Auto-generated by re:factory

## Normative Language

The key words `MUST`, `MUST NOT`, `REQUIRED`, `SHOULD`, `SHOULD NOT`,
`RECOMMENDED`, `MAY`, and `OPTIONAL` in this document are to be interpreted as
described in RFC 2119.

## 1. Project Identity

- **Name:** test-factory
- **Type:** CLI tool
- **Language:** Python 3.11+
- **Framework:** None
- **Package Manager:** uv
- **Entry Point:** `factory.cli:main`

## 2. Goals

Define a meta-harness that orchestrates coding agents through bounded,
measurable, reversible SDLC cycles.

## 3. Technical Stack

### 3.1 Dependencies

- `structlog` — structured logging
- `pydantic` — domain models

## 4. Architecture

### 4.1 Abstraction Levels

1. **CLI Layer** — command dispatch, argument parsing
2. **Data Layer** — models, store, registry
3. **Core Layer** — spec generation and validation

### 4.2 Module Graph

#### 4.2.1 cli
- **Path:** `factory/cli.py`
- **Layer:** CLI
- **Classification:** hub
- **Role:** CLI entry point for the factory
- **Exports:** main, build_parser
- **Depends on:** store, eval, spec
- **Contracts owned:** none

#### 4.2.2 store
- **Path:** `factory/store.py`
- **Layer:** Data
- **Classification:** hub
- **Role:** Experiment store managing .factory/ directory
- **Exports:** ExperimentStore
- **Depends on:** models
- **Contracts owned:** ExperimentRecord

#### 4.2.3 models
- **Path:** `factory/models.py`
- **Layer:** Data
- **Classification:** hub
- **Role:** All Pydantic v2 strict models
- **Exports:** ProjectState, FactoryConfig, EvalProfile
- **Depends on:** none
- **Contracts owned:** ProjectState, FactoryConfig, EvalProfile

#### 4.2.4 spec
- **Path:** `factory/spec/`
- **Layer:** Core
- **Classification:** leaf
- **Role:** Repo spec generation and validation
- **Exports:** generate_spec, validate_spec
- **Depends on:** models, store
- **Contracts owned:** RepoSpec

#### 4.2.5 utils
- **Path:** `factory/utils.py`
- **Layer:** Core
- **Classification:** leaf
- **Role:** Shared utility functions
- **Exports:** slugify
- **Depends on:** none
- **Contracts owned:** none

### 4.3 Dependency Edges

| Source | Target | Import Type | Coupling | Surface |
|--------|--------|-------------|----------|---------|
| cli | store | direct | strong | `ExperimentStore.begin()` |
| cli | eval | direct | strong | `run_eval()` |
| cli | spec | direct | weak | `generate_spec()` |
| store | models | direct | strong | `ExperimentRecord` |
| spec | models | direct | strong | `EvalProfile` |
| spec | store | direct | weak | `ExperimentStore` |

### 4.4 Shared Contracts

#### ProjectState
- **Defined in:** models
- **Type:** Pydantic model
- **Consumers:** cli, store, eval
- **Change Risk:** high (3 consumers)

#### FactoryConfig
- **Defined in:** models
- **Type:** Pydantic model
- **Consumers:** cli, store
- **Change Risk:** medium (2 consumers)

#### ExperimentRecord
- **Defined in:** store
- **Type:** Pydantic model
- **Consumers:** cli
- **Change Risk:** low (1 consumer)

#### RepoSpec
- **Defined in:** spec
- **Type:** Pydantic model
- **Consumers:** cli
- **Change Risk:** low (1 consumer)

### 4.5 Entry Points

| Type | Module | Detail |
|------|--------|--------|
| CLI | cli | `factory` |
| CLI | spec | `factory spec generate` |

## 5. Change Impact

| If Changed | Affects | Reason | Severity |
|------------|---------|--------|----------|
| models | cli, store, spec | Central type definitions | **high** |
| store | cli, spec | Experiment lifecycle interface | **medium** |
| cli | — | Top-level entry point | **low** |
| spec | — | No dependents | **low** |
| utils | — | No dependents | **low** |

## 6. Coupling Metrics

| Module | Ca (afferent) | Ce (efferent) | I (instability) | Classification |
|--------|--------------|--------------|-----------------|----------------|
| models | 3 | 0 | 0.00 | hub (stable core) |
| store | 2 | 1 | 0.33 | hub |
| cli | 0 | 3 | 1.00 | leaf (entry point) |
| spec | 0 | 2 | 1.00 | leaf |
| utils | 0 | 0 | 0.00 | leaf |
"""


@pytest.fixture
def project_with_spec(tmp_path: Path) -> Path:
    (tmp_path / "GRAPH-SPEC.md").write_text(SAMPLE_SPEC)
    return tmp_path


class TestGetImpact:
    def test_hub_module_with_many_dependents(self, project_with_spec: Path) -> None:
        result = get_impact("models", project_with_spec)
        assert "## Impact: models" in result
        assert "**Classification:** hub" in result
        assert "### Dependencies (imports)" in result
        assert "- None" in result.split("### Dependencies (imports)")[1].split("###")[0]
        assert "### Dependents (imported by)" in result
        assert "cli" in result.split("### Dependents (imported by)")[1]
        assert "store" in result.split("### Dependents (imported by)")[1]
        assert "spec" in result.split("### Dependents (imported by)")[1]

    def test_leaf_module_no_dependents(self, project_with_spec: Path) -> None:
        result = get_impact("utils", project_with_spec)
        assert "## Impact: utils" in result
        assert "**Classification:** leaf" in result
        dependents_section = result.split("### Dependents (imported by)")[1]
        assert "- None" in dependents_section.split("###")[0]

    def test_module_with_dependencies(self, project_with_spec: Path) -> None:
        result = get_impact("cli", project_with_spec)
        deps_section = result.split("### Dependencies (imports)")[1].split("###")[0]
        assert "store" in deps_section
        assert "eval" in deps_section
        assert "spec" in deps_section

    def test_contracts_owned(self, project_with_spec: Path) -> None:
        result = get_impact("models", project_with_spec)
        assert "### Contracts Owned" in result
        assert "ProjectState" in result
        assert "FactoryConfig" in result

    def test_no_contracts_owned(self, project_with_spec: Path) -> None:
        result = get_impact("utils", project_with_spec)
        assert "### Contracts Owned" not in result

    def test_change_impact_section(self, project_with_spec: Path) -> None:
        result = get_impact("models", project_with_spec)
        assert "### Change Impact" in result
        impact_section = result.split("### Change Impact")[1]
        assert "severity" in impact_section.lower() or "high" in impact_section.lower()

    def test_module_not_found(self, project_with_spec: Path) -> None:
        with pytest.raises(ValueError, match="Module 'nonexistent' not found"):
            get_impact("nonexistent", project_with_spec)

    def test_case_insensitive_lookup(self, project_with_spec: Path) -> None:
        result = get_impact("CLI", project_with_spec)
        assert "## Impact: cli" in result

    def test_spec_file_not_found(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            get_impact("models", tmp_path)

    def test_module_role_included(self, project_with_spec: Path) -> None:
        result = get_impact("store", project_with_spec)
        assert "**Role:** Experiment store managing .factory/ directory" in result

    def test_module_path_included(self, project_with_spec: Path) -> None:
        result = get_impact("store", project_with_spec)
        assert "**Path:** `factory/store.py`" in result

    def test_compact_output(self, project_with_spec: Path) -> None:
        result = get_impact("models", project_with_spec)
        lines = result.strip().splitlines()
        assert len(lines) < 30


class TestWorkflowSpecAwareness:
    """Verify that workflow nodes reference GRAPH-SPEC.md in prompt_template."""

    def test_build_researchers_mention_spec(self) -> None:
        from factory.workflow.definitions import build_workflow

        wf = build_workflow()
        for nid in ("researcher_similar", "researcher_techstack", "researcher_pitfalls"):
            node = wf.nodes[nid]
            assert "GRAPH-SPEC.md" in node.prompt_template

    def test_improve_researcher_mentions_spec(self) -> None:
        from factory.workflow.definitions import improve_workflow

        wf = improve_workflow()
        assert "GRAPH-SPEC.md" in wf.nodes["researcher"].prompt_template

    def test_build_strategist_mentions_spec(self) -> None:
        from factory.workflow.definitions import build_workflow

        wf = build_workflow()
        assert "GRAPH-SPEC Diff" in wf.nodes["strategist"].prompt_template

    def test_improve_strategist_mentions_spec(self) -> None:
        from factory.workflow.definitions import improve_workflow

        wf = improve_workflow()
        assert "GRAPH-SPEC Diff" in wf.nodes["strategist"].prompt_template

    def test_build_has_spec_gate(self) -> None:
        from factory.workflow.definitions import build_workflow

        wf = build_workflow()
        assert "gate_spec_exists" in wf.nodes
        assert "generate_spec" in wf.nodes
        assert "gate_spec_updated" in wf.nodes
        assert wf.start_node == "gate_spec_exists"

    def test_improve_has_spec_gate(self) -> None:
        from factory.workflow.definitions import improve_workflow

        wf = improve_workflow()
        assert "gate_spec_exists" in wf.nodes
        assert "generate_spec" in wf.nodes
        assert "gate_spec_updated" in wf.nodes
        assert wf.start_node == "gate_spec_exists"
