"""Tests for factory.spec.parser — Markdown parsing of SPEC.md."""

from __future__ import annotations

from pathlib import Path

import pytest

from factory.spec.parser import (
    RepoSpec,
    parse_spec,
)

SAMPLE_SPEC = """\
# SPEC — test-factory

Status: Draft | Auto-generated by re:factory

## Normative Language

The key words `MUST`, `MUST NOT`, `REQUIRED`, `SHOULD`, `SHOULD NOT`,
`RECOMMENDED`, `MAY`, and `OPTIONAL` in this document are to be interpreted as
described in RFC 2119.

`Implementation-defined` means the behavior is part of the implementation
contract, but this specification does not prescribe one universal policy.

## 1. Problem Statement

test-factory is a meta-harness that orchestrates coding agents through bounded,
measurable, reversible SDLC cycles.

It solves four operational problems: It turns experiment execution into a
repeatable workflow instead of ad-hoc scripts. It isolates each hypothesis in
its own experiment directory. It enforces keep/revert decisions with eval
evidence. It provides enough observability to debug agent runs.

**Important boundary:** test-factory does not call LLM APIs directly — it
spawns CLI subprocesses. It does not sandbox agent execution.

## 2. Goals and Non-Goals

### 2.1 Goals

- Orchestrate coding agents through explicit execution contracts with budget controls
- Record explicit keep/revert decisions with supporting evidence
- Maintain durable memory through playbooks, archives, and observations
- Detect project state and route to the correct workflow automatically
- Generate behavioral specifications that dissolve graph knowledge into prose

### 2.2 Non-Goals

- Prescribing a specific agent runtime — Claude, Codex, and OpenCode are all supported
- Requiring a hosted service or database — the system is filesystem-first by design
- Multi-repository orchestration as a core requirement

### 2.3 Design Philosophy

Filesystem-first, no database required. Agents run unsandboxed with trust
boundaries enforced by hard constraints in agent prompts.

## 3. Project Identity

- **Name:** test-factory
- **Type:** CLI tool
- **Language:** Python 3.11+
- **Framework:** None
- **Package Manager:** uv
- **Entry Point:** `factory.cli:main`

## 4. Technical Stack

### 4.1 Dependencies

- `structlog` — structured logging
- `pydantic` — domain models

### 4.2 External Dependencies

- `claude` CLI — agent subprocess runtime

## 5. Architecture Overview

### 5.1 Abstraction Levels

1. **CLI Layer** — command dispatch, argument parsing
2. **Data Layer** — models, store, registry
3. **Core Layer** — spec generation and validation

### 5.2 Data Flow Summary

CLI receives user commands, dispatches to the appropriate workflow. The workflow
reads project state, invokes agents as subprocesses, and writes results to
the .factory/ directory. The store manages experiment lifecycle.

## 6. Domain Model

### 6.1 ProjectState

- **Defined in:** models
- **Type:** Enum
- **Values:** NO_REPO, REPO_INCOMPLETE, NO_FACTORY, EVALS_PENDING_REVIEW, HAS_FACTORY
- ProjectState MUST be checked in order: NO_REPO before EVALS_PENDING_REVIEW

### 6.2 FactoryConfig

- **Defined in:** models
- **Type:** Pydantic BaseModel
- **Fields:**
  - `goal`: `str` — project improvement goal
  - `scope`: `str` — allowed modification scope
  - `eval_command`: `str` — command to run evaluation
  - `threshold`: `float` = `0.0` — minimum acceptable score
- FactoryConfig MUST be parsed from factory.md via ConfigDict(strict=True)

### 6.3 ExperimentRecord

- **Defined in:** store
- **Type:** Pydantic BaseModel
- **Fields:**
  - `id`: `int` — experiment number
  - `hypothesis`: `str` — what is being tested
  - `verdict`: `str` — keep or revert
- ExperimentRecord MUST be serializable to TSV by ExperimentStore

## 7. State Machines and Lifecycles

### 7.1 Project State Detection

```
NO_REPO → REPO_INCOMPLETE → NO_FACTORY → EVALS_PENDING_REVIEW → HAS_FACTORY
```

- **Governed by:** state.py
- detect_state() MUST check states in enum order
- Each state transition is triggered by the presence of specific files

### 7.2 Experiment Lifecycle

```
begin → build → eval → verdict(keep/revert) → finalize
```

- **Governed by:** store.py
- begin() MUST create the experiment directory before any agent runs
- finalize() MUST NOT be called without a verdict

## 8. Module Specifications

### 8.1 cli
- **Path:** `factory/cli.py`
- **Layer:** CLI
- **Role:** CLI entry point for the factory

This module MUST dispatch all subcommands through a handler dict. It reads
FactoryConfig (Section 6.2) on startup and MUST fail with a clear error if
factory.md is malformed. It is consumed by the entry point script registered
in pyproject.toml.

### 8.2 store
- **Path:** `factory/store.py`
- **Layer:** Data
- **Role:** Experiment store managing .factory/ directory
- **Consumes:** models for ExperimentRecord and FactoryConfig
- **Consumed by:** cli for experiment lifecycle dispatch

ExperimentStore MUST create .factory/ on first begin() call. Adding a field
to ExperimentRecord MUST be accompanied by a TSV_COLUMNS update.

### 8.3 models
- **Path:** `factory/models.py`
- **Layer:** Data
- **Role:** All Pydantic v2 strict models
- **Consumes:** none
- **Consumed by:** store, cli, spec

All models MUST use ConfigDict(strict=True, extra="forbid"). New model
fields SHOULD have explicit defaults to maintain backward compatibility.

### 8.4 spec
- **Path:** `factory/spec/`
- **Layer:** Core
- **Role:** Repo spec generation and validation
- **Consumes:** models for EvalProfile, store for ExperimentStore
- **Consumed by:** cli

The spec module MUST produce SPEC.md with RFC 2119 normative language.
Validation MUST check path existence for all declared modules.

### 8.5 utils
- **Path:** `factory/utils.py`
- **Layer:** Core
- **Role:** Shared utility functions
- **Consumes:** none
- **Consumed by:** none

Utility functions SHOULD be pure and stateless.

## 9. Shared Contracts

### 9.1 ProjectState
- **Defined in:** models
- **Type:** Pydantic model
- **Consumers:** cli, store, eval

ProjectState MUST be the first thing checked in any workflow dispatch.
Changes to ProjectState values MUST be accompanied by updates to detect_state().

### 9.2 FactoryConfig
- **Defined in:** models
- **Type:** Pydantic model
- **Consumers:** cli, store

FactoryConfig SHOULD be treated as immutable after initial parsing.

### 9.3 ExperimentRecord
- **Defined in:** store
- **Type:** Pydantic model
- **Consumers:** cli

ExperimentRecord changes MUST maintain TSV round-trip fidelity.

## 10. Configuration Specification

### 10.1 Configuration Sources and Precedence

CLI flag > env var > config.toml > hardcoded default

### 10.2 Core Config Fields

- `FACTORY_RUNNER` — which CLI backend to use (default: claude)
- `FACTORY_PROJECTS_DIR` — where to create new projects

### 10.3 Validation and Error Surface

Missing required fields MUST produce actionable error messages.

## 11. Entry Points

| Type | Module | Detail |
|------|--------|--------|
| CLI | cli | `factory` |
| CLI | spec | `factory spec generate` |

## 12. Failure Model and Recovery

### 12.1 Failure Classes

- Agent timeout — subprocess exceeds time limit
- Eval failure — score.py returns non-zero exit code
- Config parse error — factory.md is malformed

### 12.2 Recovery Behavior

Agent timeouts SHOULD be retried once. Eval failures MUST trigger revert.

### 12.3 Restart and Resume Semantics

Checkpoint MUST save enough state to resume from the last completed step.

## 13. Security and Safety

### 13.1 Trust Boundaries

Agents run unsandboxed. The factory MUST NOT pass secrets via command-line arguments.

### 13.2 Filesystem Safety Invariants

The factory MUST NOT modify files outside the project directory and .factory/.

### 13.3 Secret Handling

API keys SHOULD be read from environment variables or config.toml, never committed.

## 14. Test and Validation Matrix

### 14.1 Core Conformance Criteria

- All Pydantic models must round-trip through JSON
- All CLI subcommands must have test coverage

### 14.2 Test Coverage by Subsystem

- models: unit tests for serialization
- store: integration tests with tmp_path
- spec: parser tests with fixture specs

## 15. Extension Points

- Custom agent prompts via .factory/agents/<role>.md overrides
- Custom runners via the runner abstraction in factory/runners/

## 16. Implementation Checklist

### 16.1 Required for Conformance

- [ ] All models use ConfigDict(strict=True, extra="forbid")
- [ ] detect_state() checks states in enum order

### 16.2 Recommended Extensions

- [ ] Dashboard for live monitoring
- [ ] Cross-project insights aggregation

## Appendix A. Reference Algorithms

### A.1 State Detection

```
def detect_state(project_path):
    if not (project_path / ".git").exists():
        return NO_REPO
    if not has_source_files(project_path):
        return REPO_INCOMPLETE
    if not (project_path / ".factory").exists():
        return NO_FACTORY
    if not eval_profile_reviewed(project_path):
        return EVALS_PENDING_REVIEW
    return HAS_FACTORY
```
"""


@pytest.fixture
def spec_file(tmp_path: Path) -> Path:
    p = tmp_path / "SPEC.md"
    p.write_text(SAMPLE_SPEC)
    return p


class TestParseIdentity:
    def test_parses_name(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.name == "test-factory"

    def test_parses_type(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.project_type == "CLI tool"

    def test_parses_language(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.language == "Python 3.11+"

    def test_parses_framework(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.framework == "None"

    def test_parses_package_manager(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.package_manager == "uv"

    def test_parses_entry_point(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.identity.entry_point == "factory.cli:main"


class TestParseGoals:
    def test_parses_goals(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Orchestrate coding agents" in spec.goals


class TestParseAbstractionLevels:
    def test_parses_levels(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.abstraction_levels) == 3
        assert "CLI Layer" in spec.abstraction_levels
        assert "Data Layer" in spec.abstraction_levels
        assert "Core Layer" in spec.abstraction_levels


class TestParseModules:
    def test_parses_all_modules(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.modules) == 5
        names = [m.name for m in spec.modules]
        assert names == ["cli", "store", "models", "spec", "utils"]

    def test_module_path(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        cli = spec.get_module("cli")
        assert cli is not None
        assert cli.path == "factory/cli.py"

    def test_module_role(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        store = spec.get_module("store")
        assert store is not None
        assert store.role == "Experiment store managing .factory/ directory"

    def test_module_layer(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        models = spec.get_module("models")
        assert models is not None
        assert models.layer == "Data"

    def test_module_consumes(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        store = spec.get_module("store")
        assert store is not None
        assert "models" in store.consumes

    def test_module_consumed_by(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        store = spec.get_module("store")
        assert store is not None
        assert "cli" in store.consumed_by

    def test_module_behavioral_spec(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        store = spec.get_module("store")
        assert store is not None
        assert "MUST" in store.behavioral_spec

    def test_module_contracts_owned(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        cli = spec.get_module("cli")
        assert cli is not None
        assert cli.contracts_owned == []

    def test_consumes_empty(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        models = spec.get_module("models")
        assert models is not None
        assert models.consumes == "none"


class TestParseSharedContracts:
    def test_parses_all_contracts(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.shared_contracts) == 3

    def test_contract_name(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.shared_contracts[0].name == "ProjectState"

    def test_contract_defined_in(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.shared_contracts[0].defined_in == "models"

    def test_contract_consumers(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.shared_contracts[0].consumers == ["cli", "store", "eval"]


class TestParseEntryPoints:
    def test_parses_all_entry_points(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert len(spec.entry_points) == 2

    def test_entry_point_fields(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        ep = spec.entry_points[0]
        assert ep.name == "CLI"
        assert ep.module == "cli"


class TestParseProblemStatement:
    def test_parses_problem_statement(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "meta-harness" in spec.problem_statement
        assert "operational problems" in spec.problem_statement

    def test_includes_boundary(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Important boundary" in spec.problem_statement


class TestParseNonGoals:
    def test_parses_non_goals(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "agent runtime" in spec.non_goals
        assert "filesystem-first" in spec.non_goals


class TestParseDesignPhilosophy:
    def test_parses_design_philosophy(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Filesystem-first" in spec.design_philosophy


class TestParseDataFlowSummary:
    def test_parses_data_flow(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "CLI receives" in spec.data_flow_summary


class TestParseDomainModel:
    def test_parses_domain_model(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "ProjectState" in spec.domain_model_raw
        assert "FactoryConfig" in spec.domain_model_raw
        assert "ExperimentRecord" in spec.domain_model_raw


class TestParseStateMachines:
    def test_parses_state_machines(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Project State Detection" in spec.state_machines_raw
        assert "Experiment Lifecycle" in spec.state_machines_raw


class TestParseConfigurationSpec:
    def test_parses_configuration(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "CLI flag" in spec.configuration_spec
        assert "FACTORY_RUNNER" in spec.configuration_spec


class TestParseFailureModel:
    def test_parses_failure_model(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Agent timeout" in spec.failure_model
        assert "Recovery" in spec.failure_model


class TestParseSecurity:
    def test_parses_security(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Trust Boundaries" in spec.security
        assert "Secret Handling" in spec.security


class TestParseTestMatrix:
    def test_parses_test_matrix(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Conformance Criteria" in spec.test_matrix


class TestParseExtensionPoints:
    def test_parses_extension_points(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Custom agent prompts" in spec.extension_points


class TestParseImplementationChecklist:
    def test_parses_checklist(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert "Required for Conformance" in spec.implementation_checklist


class TestGetModule:
    def test_case_insensitive(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.get_module("CLI") is not None
        assert spec.get_module("cli") is not None

    def test_not_found(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        assert spec.get_module("nonexistent") is None


class TestParseSpecErrors:
    def test_file_not_found(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            parse_spec(tmp_path / "missing.md")

    def test_empty_spec(self, tmp_path: Path) -> None:
        p = tmp_path / "empty.md"
        p.write_text("")
        spec = parse_spec(p)
        assert isinstance(spec, RepoSpec)
        assert spec.modules == []
        assert spec.dependency_edges == []

    def test_spec_with_no_tables(self, tmp_path: Path) -> None:
        p = tmp_path / "notables.md"
        p.write_text(
            "# SPEC\n\n## 8. Module Specifications\n\n### 8.1 alpha\n- **Path:** `src/alpha`\n"
        )
        spec = parse_spec(p)
        assert len(spec.modules) == 1
        assert spec.modules[0].name == "alpha"
        assert spec.dependency_edges == []


class TestBackwardCompatibility:
    def test_old_format_modules_section(self, tmp_path: Path) -> None:
        """Ensure the parser still handles the old ## Modules / ### name format."""
        p = tmp_path / "old_format.md"
        p.write_text(
            "# Repo Spec\n\n## Modules\n\n### cli\n"
            "- **Path:** factory/cli.py\n- **Role:** Entry point\n"
            "- **Depends on:** store\n"
        )
        spec = parse_spec(p)
        assert len(spec.modules) == 1
        assert spec.modules[0].name == "cli"
        assert spec.modules[0].depends_on == ["store"]

    def test_old_graph_spec_format(self, tmp_path: Path) -> None:
        """Ensure old GRAPH-SPEC.md with tables still parses correctly."""
        p = tmp_path / "GRAPH-SPEC.md"
        p.write_text(
            "# GRAPH-SPEC\n\n"
            "## 1. Project Identity\n\n"
            "- **Name:** old-project\n"
            "- **Type:** CLI tool\n\n"
            "## 2. Goals\n\nSome goals here.\n\n"
            "## 4. Architecture\n\n"
            "### 4.1 Abstraction Levels\n\n"
            "1. **CLI** — commands\n\n"
            "### 4.2 Module Graph\n\n"
            "#### 4.2.1 cli\n"
            "- **Path:** `src/cli.py`\n"
            "- **Classification:** hub\n"
            "- **Exports:** main\n"
            "- **Depends on:** models\n\n"
            "### 4.3 Dependency Edges\n\n"
            "| Source | Target | Import Type | Coupling | Surface |\n"
            "|--------|--------|-------------|----------|---------|\n"
            "| cli | models | direct | strong | `Model` |\n\n"
            "## 5. Change Impact\n\n"
            "| If Changed | Affects | Reason | Severity |\n"
            "|------------|---------|--------|----------|\n"
            "| models | cli | types | **high** |\n\n"
            "## 6. Coupling Metrics\n\n"
            "| Module | Ca (afferent) | Ce (efferent) | I (instability) | Classification |\n"
            "|--------|--------------|--------------|-----------------|----------------|\n"
            "| models | 1 | 0 | 0.00 | hub |\n"
            "| cli | 0 | 1 | 1.00 | leaf |\n"
        )
        spec = parse_spec(p)
        assert spec.identity.name == "old-project"
        assert len(spec.modules) == 1
        assert spec.modules[0].classification == "hub"
        assert spec.modules[0].exports == ["main"]
        assert spec.modules[0].depends_on == ["models"]
        assert len(spec.dependency_edges) == 1
        assert spec.dependency_edges[0].source == "cli"
        assert len(spec.change_impact) == 1
        assert spec.change_impact[0].module == "models"
        assert len(spec.coupling_metrics) == 2
        assert spec.coupling_metrics[0].ca == 1

    def test_new_format_returns_empty_legacy_fields(self, spec_file: Path) -> None:
        """New behavioral format returns empty lists for legacy table-based fields."""
        spec = parse_spec(spec_file)
        assert spec.dependency_edges == []
        assert spec.change_impact == []
        assert spec.coupling_metrics == []


class TestPathExtractionFromBacktickHeadings:
    def test_extracts_path_from_backtick_heading(self, tmp_path: Path) -> None:
        p = tmp_path / "spec.md"
        p.write_text(
            "# SPEC\n\n## 8. Module Specifications\n\n"
            "### 8.1 `factory/state.py` — Project State Detection\n"
            "- **Role:** Detects project state\n"
        )
        spec = parse_spec(p)
        assert len(spec.modules) == 1
        assert spec.modules[0].path == "factory/state.py"
        assert spec.modules[0].name == "`factory/state.py` — Project State Detection"

    def test_no_backtick_path_when_field_exists(self, tmp_path: Path) -> None:
        p = tmp_path / "spec.md"
        p.write_text(
            "# SPEC\n\n## 8. Module Specifications\n\n### 8.1 cli\n- **Path:** `factory/cli.py`\n"
        )
        spec = parse_spec(p)
        assert spec.modules[0].path == "factory/cli.py"

    def test_ignores_backtick_without_path_pattern(self, tmp_path: Path) -> None:
        p = tmp_path / "spec.md"
        p.write_text(
            "# SPEC\n\n## 8. Module Specifications\n\n"
            "### 8.1 `some-name` — Description\n"
            "- **Role:** Something\n"
        )
        spec = parse_spec(p)
        assert spec.modules[0].path == ""


class TestGetModuleByPath:
    def test_finds_module_by_path(self, tmp_path: Path) -> None:
        p = tmp_path / "spec.md"
        p.write_text(
            "# SPEC\n\n## 8. Module Specifications\n\n"
            "### 8.1 `factory/state.py` — Project State Detection\n"
            "- **Role:** Detects project state\n"
        )
        spec = parse_spec(p)
        mod = spec.get_module("factory/state.py")
        assert mod is not None
        assert mod.path == "factory/state.py"

    def test_path_lookup_case_insensitive(self, tmp_path: Path) -> None:
        p = tmp_path / "spec.md"
        p.write_text(
            "# SPEC\n\n## 8. Module Specifications\n\n"
            "### 8.1 `Factory/State.py` — State Detection\n"
            "- **Role:** Detects state\n"
        )
        spec = parse_spec(p)
        assert spec.get_module("factory/state.py") is not None

    def test_name_match_takes_priority_over_path(self, spec_file: Path) -> None:
        spec = parse_spec(spec_file)
        mod = spec.get_module("cli")
        assert mod is not None
        assert mod.name == "cli"


class TestParseCommaListBackticks:
    def test_strips_backticks_per_item(self) -> None:
        from factory.spec.parser import _parse_comma_list

        result = _parse_comma_list("`models`, `store`, `cli`")
        assert result == ["models", "store", "cli"]

    def test_handles_mixed_backtick_and_plain(self) -> None:
        from factory.spec.parser import _parse_comma_list

        result = _parse_comma_list("`models`, store, `cli`")
        assert result == ["models", "store", "cli"]

    def test_single_backtick_item(self) -> None:
        from factory.spec.parser import _parse_comma_list

        result = _parse_comma_list("`models`")
        assert result == ["models"]
