"""LUMEN RL Workflow - Learning-based Universal Modeling and Evolution eNgine.

RL training system for scientific discovery tasks (starting with Einstein Arena).

All nodes read configuration from .factory/lumen/current_run/config.json,
which is generated by the preflight node at the start of each run.

Environment: Uses uv virtual environment for Python execution.
Default path: factory/lumen/.venv/bin/python
Override via: LUMEN_PYTHON environment variable
"""

import os
from typing import Any

from factory.models import ProjectState
from factory.workflow.primitives import (
    AgentNode,
    AgentRole,
    Edge,
    FnNode,
    GateNode,
    VerdictType,
    Workflow,
)

meta = {
    "name": "lumen",
    "description": "LUMEN: Learning-based Universal Modeling and Evolution eNgine - RL training for scientific discovery",
}

# Shorthand for the run config path (relative to project root)
_CFG = ".factory/lumen/current_run/config.json"
_STATE = ".factory/lumen/current_run/state.json"

# Lumen Python interpreter path (uv venv in factory/lumen/.venv)
# Can be overridden via LUMEN_PYTHON environment variable
# Default: {remote-factory-root}/factory/lumen/.venv/bin/python
def _get_lumen_python() -> str:
    if "LUMEN_PYTHON" in os.environ:
        return os.environ["LUMEN_PYTHON"]
    # Assume we're being called from remote-factory root
    # workflow.py is in: remote-factory/factory/workflow/contributed/lumen/
    # .venv is in:       remote-factory/factory/lumen/.venv/
    return "factory/lumen/.venv/bin/python"

_LUMEN_PYTHON = _get_lumen_python()


def workflow() -> Workflow:
    """Build the Lumen workflow graph."""
    nodes: dict[str, Any] = {}
    edges: list[Edge] = []

    # ── Node 0: Setup ─────────────────────────────────────────
    # Preflight (checks uv venv, GPUs, run dir, resolved config) + SOTA update.
    nodes["setup"] = FnNode(
        id="setup",
        command=(
            "cd {project_path} && "
            # Preflight runs in refactory env (checks if lumen venv exists)
            "python3 -m factory.lumen.preflight --project-path {project_path} && "
            # SOTA update runs in lumen env (may need numpy/scientific libs)
            f"TASK=$({_LUMEN_PYTHON} -c \""
            f"import json; print(json.load(open('{_CFG}'))['task_name'])"
            '") && '
            f"{_LUMEN_PYTHON} benchmarks/einsteinarena/tools/add_sota_to_instruction.py $TASK || true"
        ),
        writes={".factory/lumen/current_run/config.json", ".factory/lumen/current_run/state.json"},
    )

    # ── Node 1: Config Gate ────────────────────────────────────
    # Interactive: CEO presents the resolved config to the user for approval.
    # Headless (auto_approve=True): auto-proceeds.
    nodes["config_gate"] = GateNode(
        id="config_gate",
        evaluator_type="user",
        reads={_CFG},
    )

    # ── Node 2: Lumen Context Agent ────────────────────────────
    nodes["lumen_context_agent"] = AgentNode(
        id="lumen_context_agent",
        role=AgentRole.LUMEN_CONTEXT_AGENT,
        model="opus",
        timeout=1800,
        prompt_template=(
            "You are the Lumen Context Agent. Generate 8 optimization prompts.\n\n"
            f"Read the run config at {_CFG} to find task_name and iteration.\n"
            "Read: benchmarks/einsteinarena/<task_name>/instruction.md\n"
            f"Read: {_STATE} for current iteration.\n\n"
            "If iteration > 0, read the previous iteration's evaluation_results.json "
            "from .factory/lumen/current_run/iteration_<prev>/evaluation_results.json\n\n"
            "Output: .factory/lumen/current_run/iteration_<current>/prompts.json\n\n"
            "Follow the format specified in factory/agents/prompts/lumen_context_agent.md"
        ),
        reads={_CFG, _STATE},
        writes={".factory/lumen/current_run/iteration_*/prompts.json"},
        transcript_dir="{project_path}/.factory/lumen/current_run/transcripts",
    )

    # ── Node 3: RL Training ─────────────────────────────────────
    # CRITICAL: Must run in lumen env (needs numpy, verl, vLLM)
    nodes["rl_train"] = FnNode(
        id="rl_train",
        command=(
            "cd {project_path} && "
            f"{_LUMEN_PYTHON} -m factory.lumen.train "
            f"--config {_CFG}"
        ),
        reads={_CFG, _STATE, ".factory/lumen/current_run/iteration_*/prompts.json"},
        writes={
            ".factory/lumen/current_run/iteration_*/rollouts.jsonl",
            ".factory/lumen/current_run/iteration_*/evaluation_results.json",
        },
    )

    # ── Node 4: Check Gate ──────────────────────────────────────
    # Uses only stdlib - can run in any Python
    nodes["check_gate"] = GateNode(
        id="check_gate",
        evaluator_type="fn",
        evaluator_command=(
            "cd {project_path} && "
            "python3 -c \""
            f"import json, re, pathlib;"
            f"cfg = json.load(open('{_CFG}'));"
            f"state = json.load(open('{_STATE}'));"
            "task_name = cfg['task_name'];"
            "it = state['iteration'];"
            "results = json.load(open(f'.factory/lumen/current_run/iteration_{it}/evaluation_results.json'));"
            "md = open(f'benchmarks/einsteinarena/{task_name}/instruction.md').read();"
            "sota_match = re.search(r'Current best score.*?([0-9.eE+-]+)', md);"
            "min_imp_match = re.search(r'Minimum improvement.*?([0-9.eE+-]+)', md);"
            "dir_match = re.search(r'Scoring Direction.*?(MAXIMIZE|MINIMIZE)', md);"
            "sota = float(sota_match.group(1)) if sota_match else None;"
            "min_imp = float(min_imp_match.group(1)) if min_imp_match else 1e-10;"
            "direction = dir_match.group(1) if dir_match else 'MAXIMIZE';"
            "best = results['best_score'];"
            "if sota is None:"
            "  print('pass: No SOTA yet, any valid score is success');"
            "else:"
            "  success = (best > sota + min_imp) if direction == 'MAXIMIZE' else (best < sota - min_imp);"
            "  if success:"
            "    print('pass: Score improved beyond SOTA');"
            "  elif it >= 2:"
            "    print('halt: Max iterations reached without improvement');"
            "  else:"
            "    state['iteration'] = it + 1;"
            f"    json.dump(state, open('{_STATE}', 'w'));"
            "    print('reloop: Need more iterations');"
            "\""
        ),
        reads={_CFG, _STATE},
    )

    # ── Edges ───────────────────────────────────────────────────
    edges = [
        Edge(source="setup", target="config_gate"),
        Edge(source="config_gate", target="lumen_context_agent"),
        Edge(source="lumen_context_agent", target="rl_train"),
        Edge(source="rl_train", target="check_gate"),
        Edge(source="check_gate", target="lumen_context_agent", condition=VerdictType.RELOOP),
    ]

    def trigger(state: ProjectState, ctx: dict[str, Any]) -> bool:
        return ctx.get("mode") == "lumen"

    return Workflow(
        name="lumen",
        nodes=nodes,
        edges=edges,
        start_node="setup",
        terminal=True,
        trigger=trigger,
    )
